# -*- coding: utf-8 -*-
"""VADER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qFh19PpzbeaCZUks-_cqN37F879fD0EP
"""

import pandas as pd
import numpy as np
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

s = SentimentIntensityAnalyzer()




from google.colab import files
import io


uploaded = files.upload()

df = pd.read_csv(io.BytesIO(uploaded['fkartdata.csv']))
print(df)


df['scores'] = df["Review"].apply(lambda review: s.polarity_scores("Review"))

df.head()

df['compound']  = df['scores'].apply(lambda score_dict: score_dict['compound'])

df.head()

df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')

df.head()

df['scores'] = df["Review"].apply(lambda review: s.polarity_scores("Review"))

df.head()

df['compound']  = df['scores'].apply(lambda score_dict: score_dict['compound'])

df.head()

print(df)

df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')

df.head()
print(df)

review = 'Colour of the shirt is not as shown in image. Cloth & fitting is good'
# Obtain the sid scores for your review
s.polarity_scores(review)